### ISSUE TITLE
在安卓手机上和windows电脑上chrome和edge都无法正常显示服务器数量

### ISSUE THREAD

**Issue by Venompool888** [akile-network/akile_monitor_fe#1]
发现一个问题，不知道是不是我独有的，部署的前端在chrome和edge上显示不出服务器总数，均为0，安卓手机和windows电脑都这样，别人部署的打开也是显示0。用夸克浏览器的话电脑上也是0，手机上就可以显示详细正确内容。安卓手机via可以正常显示
我的https://aktanzhen.pages.dev/ 
别人的 https://tz-ezr.pages.dev/

**Comment by miuss** [comment]
我看您，后端没有https但是前端有https，你需要把后端的https加上，并修改ws:// 为 wss://
