### ISSUE TITLE
在线状态错误

### ISSUE THREAD

**Issue by Luochancy** [akile-network/akile_monitor_fe#6]
ak的香港作为主控，被控为ak的日本。安装后查看被控日志有正常反馈，前端查看上报数据为离线，但是流量与占用率有在跑

![Screenshot_2024-12-09-07-37-45-640_mark via](https://github.com/user-attachments/assets/78461456-bdc4-43e3-af39-23bb282b26ee)

**Comment by GenshinMinecraft** [comment]
尝试检查被控端与本地的时间，当获取时间戳有误时会有该情况
